export const unoClassRules: Record<string, Record<string, string>> = {
  "art-frame": {
    "display": "flex",
    "justify-content": "center",
    "padding": "28px",
    "margin-top": "28px",
  },
  "brand": {
    "display": "inline-flex",
    "align-items": "center",
    "gap": "10px",
    "font-weight": "660",
    "letter-spacing": "-0.02em",
  },
  "brand-name": {
    "font-size": "1.02rem",
  },
  "btn": {
    "display": "inline-flex",
    "align-items": "center",
    "justify-content": "center",
    "padding": "14px 26px",
    "border-radius": "999px",
    "font-weight": "620",
    "letter-spacing": "-0.01em",
    "will-change": "transform",
    "transition": "background 0.25s ease, border-color 0.25s ease",
  },
  "btn-cissa": {
    "color": "#ffd9c2",
    "border-color": "rgba(255, 154, 98, 0.42)",
  },
  "btn-cupboard": {
    "color": "#c4f5e7",
    "border-color": "rgba(110, 231, 200, 0.4)",
  },
  "btn-ghost": {
    "color": "#e3e8f8",
  },
  "card": {
    "display": "flex",
    "flex-direction": "column",
    "gap": "12px",
    "padding": "26px",
    "min-height": "320px",
    "transition": "border-color 0.3s ease, transform 0.3s ease",
  },
  "card-art": {
    "margin-top": "auto",
    "display": "flex",
    "justify-content": "center",
  },
  "card-go": {
    "font-size": "12.5px",
    "letter-spacing": "0.12em",
    "color": "var(--dim)",
    "transition": "color 0.25s ease",
  },
  "card-kicker": {
    "font-size": "11.5px",
    "letter-spacing": "0.2em",
    "color": "var(--dim)",
  },
  "card-title": {
    "font-size": "2.1rem",
    "font-weight": "680",
    "letter-spacing": "-0.03em",
  },
  "cissa-object": {
    "transform": "rotate(-4deg)",
  },
  "closing": {
    "text-align": "center",
    "padding-bottom": "9rem",
  },
  "closing-link": {
    "display": "inline-flex",
    "gap": "90px",
    "border-bottom": "1px solid",
    "padding-bottom": "10px",
  },
  "closing-mark": {
    "position": "absolute",
    "right": "9vw",
    "top": "50%",
    "width": "19vw",
    "height": "19vw",
    "transform": "translateY(-40%) rotate(15deg)",
  },
  "closing-playground": {
    "position": "relative",
    "display": "grid",
    "grid-template-columns": "minmax(0, 1.7fr) minmax(0, 1fr)",
    "background": "#d9edb1",
    "padding-right": "3vw",
  },
  "companion-story": {
    "display": "grid",
    "grid-template-columns": "1fr 1fr",
    "background": "#e2e3d9",
    "min-height": "700px",
  },
  "companion-switch": {
    "position": "relative",
    "display": "grid",
    "grid-template-columns": "1fr 1fr",
    "border-bottom": "1px solid #25292250",
    "margin-block": "60px 42px",
    "gap": "28px",
  },
  "companions-heading": {
    "display": "flex",
    "align-items": "end",
    "justify-content": "space-between",
    "gap": "30px",
    "margin-block": "70px 25px",
  },
  "companions-section": {
    "padding": "60px 5vw 90px",
    "scroll-margin-top": "20px",
  },
  "cupboard-object": {
    "width": "min(42vw, 530px)",
    "transform": "rotate(3deg)",
  },
  "cupboard-status": {
    "padding": "45px 5vw 65px",
    "border-top": "1px solid #25292244",
  },
  "detail-plus": {
    "font-size": "24px",
    "transition": "transform 0.25s",
  },
  "development-note": {
    "max-width": "58ch",
    "margin-top": "20px",
    "color": "#555b50",
  },
  "dim": {
    "color": "var(--dim)",
  },
  "display": {
    "font-size": "clamp(2.2rem, 4.6vw, 3.6rem)",
    "font-weight": "680",
    "letter-spacing": "-0.03em",
    "line-height": "1.04",
    "margin": "16px 0 18px",
    "text-wrap": "balance",
  },
  "duo": {
    "display": "grid",
    "grid-template-columns": "1fr 1fr",
    "gap": "22px",
  },
  "explore-link": {
    "display": "flex",
    "align-items": "center",
    "gap": "40px",
    "font-size": "13px",
    "border-bottom": "1px solid #25292260",
    "padding-bottom": "12px",
  },
  "fancy-label": {
    "display": "inline-block",
    "vertical-align": "bottom",
  },
  "fancy-label-island": {
    "display": "inline-block",
    "vertical-align": "bottom",
  },
  "feature": {
    "padding": "22px",
  },
  "feature-link": {
    "display": "flex",
    "align-items": "center",
  },
  "features": {
    "display": "grid",
    "grid-template-columns": "repeat(3, 1fr)",
    "gap": "18px",
  },
  "field-journal": {
    "padding": "80px 5vw 100px",
  },
  "field-journal-grid": {
    "display": "grid",
    "grid-template-columns": "minmax(0, 1.1fr) minmax(0, 0.85fr)",
    "align-items": "start",
    "gap": "7vw",
  },
  "footer": {
    "border-top": "1px solid var(--line)",
    "background": "rgba(7, 11, 24, 0.6)",
    "backdrop-filter": "blur(12px)",
    "-webkit-backdrop-filter": "blur(12px)",
  },
  "footer-base": {
    "display": "flex",
    "flex-wrap": "wrap",
    "justify-content": "space-between",
    "gap": "10px",
    "padding-block": "20px",
    "border-top": "1px solid var(--line)",
    "font-size": "12px",
  },
  "footer-col": {
    "display": "flex",
    "flex-direction": "column",
    "gap": "10px",
  },
  "footer-grid": {
    "display": "grid",
    "grid-template-columns": "2fr 1fr 1fr 1fr",
    "gap": "36px",
    "padding-block": "56px",
  },
  "footer-line": {
    "color": "var(--muted)",
    "font-size": "0.95rem",
    "max-width": "40ch",
    "margin-bottom": "10px",
  },
  "glass": {
    "position": "relative",
    "background": "var(--glass-bg)",
    "border": "1px solid var(--glass-border)",
    "border-radius": "var(--radius)",
    "backdrop-filter": "blur(18px) saturate(150%)",
    "-webkit-backdrop-filter": "blur(18px) saturate(150%)",
    "box-shadow": "0 24px 70px rgba(3, 7, 18, 0.38), inset 0 1px 0 rgba(255, 255, 255, 0.12)",
  },
  "glass-lens": {
    "width": "120px",
    "height": "66px",
    "border-radius": "50%",
    "pointer-events": "none",
  },
  "grad": {
    "background-clip": "text",
    "-webkit-background-clip": "text",
    "color": "transparent",
    "background-image": "linear-gradient(92deg, #ffb987, #8ef0d2)",
  },
  "grad-cissa": {
    "background-clip": "text",
    "-webkit-background-clip": "text",
    "color": "transparent",
    "background-image": "linear-gradient(92deg, #ffb987, #ffd9a0)",
  },
  "grad-cupboard": {
    "background-clip": "text",
    "-webkit-background-clip": "text",
    "color": "transparent",
    "background-image": "linear-gradient(92deg, #6ee7c8, #8ea2ff)",
  },
  "gravity-hint": {
    "position": "absolute",
    "top": "0",
    "right": "0",
    "font": "10px \"IBM Plex Mono\", monospace",
    "pointer-events": "none",
  },
  "gravity-mark": {
    "position": "absolute",
    "inset": "0 auto auto 0",
    "width": "clamp(105px, 14vw, 215px)",
    "aspect-ratio": "1",
    "border": "0",
    "background": "transparent",
    "padding": "12px",
    "cursor": "grab",
    "touch-action": "none",
    "will-change": "transform",
  },
  "gravity-secret": {
    "position": "absolute",
    "left": "0",
    "top": "32px",
    "max-width": "26ch",
    "font": "12px/1.5 \"IBM Plex Mono\", monospace",
  },
  "gravity-stage": {
    "position": "relative",
    "overflow": "hidden",
    "min-height": "320px",
    "margin-block": "35px",
    "border-bottom": "1px solid #25292255",
  },
  "hero": {
    "position": "relative",
    "min-height": "100svh",
    "display": "flex",
    "flex-direction": "column",
    "align-items": "center",
    "justify-content": "center",
    "text-align": "center",
    "padding": "120px 20px 90px",
    "gap": "8px",
  },
  "hero-bottomline": {
    "position": "absolute",
    "inset-inline": "3.2vw",
    "display": "flex",
    "align-items": "end",
    "justify-content": "space-between",
    "bottom": "32%",
    "animation": "intro-reveal 0.8s both",
    "opacity": "0",
    "visibility": "hidden",
  },
  "hero-cta": {
    "display": "flex",
    "flex-wrap": "wrap",
    "justify-content": "center",
    "gap": "16px",
  },
  "hero-landscape": {
    "width": "100%",
    "height": "100%",
    "object-fit": "cover",
    "object-position": "center bottom",
    "opacity": "0",
    "transition": "opacity 1.8s ease",
  },
  "hero-lens": {
    "position": "absolute",
    "left": "65%",
    "top": "49%",
    "transform": "rotate(-18deg)",
    "pointer-events": "none",
    "animation": "intro-reveal 0.8s both",
    "opacity": "0",
    "visibility": "hidden",
  },
  "hero-line": {
    "max-width": "54ch",
    "color": "#ccd3ea",
    "font-size": "clamp(1.05rem, 1.9vw, 1.3rem)",
    "line-height": "1.6",
    "text-wrap": "balance",
    "text-shadow": "0 1px 26px rgba(7, 11, 24, 0.9)",
  },
  "hero-note": {
    "font-size": "12px",
    "letter-spacing": "0.18em",
  },
  "hero-object": {
    "position": "absolute",
    "left": "50%",
    "top": "38%",
    "transform": "translate(-50%, -50%)",
  },
  "hero-page": {
    "min-height": "74svh",
  },
  "hero-sub": {
    "display": "flex",
    "flex-direction": "column",
    "align-items": "center",
    "gap": "26px",
  },
  "hero-thought": {
    "font": "clamp(20px, 2.1vw, 31px)/1.3 \"IBM Plex Mono\", monospace",
    "line-height": "1.13",
    "letter-spacing": "-0.045em",
    "width": "29%",
  },
  "hero-title": {
    "overflow": "hidden",
    "font-size": "clamp(3.4rem, 13.5vw, 11.5rem)",
    "font-weight": "700",
    "letter-spacing": "-0.048em",
    "line-height": "1",
    "padding": "0.06em 0.06em 0.14em",
    "text-shadow": "0 4px 60px rgba(255, 214, 170, 0.22)",
  },
  "hero-topline": {
    "position": "absolute",
    "inset-inline": "3.2vw",
    "display": "flex",
    "align-items": "start",
    "justify-content": "space-between",
    "top": "18%",
    "animation": "intro-reveal 0.8s both",
    "opacity": "0",
    "visibility": "hidden",
  },
  "home": {
    "--paper": "#eeece4",
    "--home-ink": "#252922",
    "background": "var(--paper)",
    "color": "var(--home-ink)",
    "font-family": "\"DM Sans\", sans-serif",
    "line-height": "1.45",
    "color-scheme": "light",
  },
  "home-atmosphere": {
    "position": "absolute",
    "inset": "0 0 27%",
    "z-index": "-1",
    "background": "#d9e3df",
  },
  "home-brand": {
    "display": "inline-flex",
    "gap": "8px",
    "align-items": "center",
    "font-size": "23px",
    "font-weight": "750",
    "letter-spacing": "-0.065em",
  },
  "home-closing": {
    "position": "relative",
    "background": "#d9edb1",
    "padding": "55px 5vw 65px",
    "overflow": "hidden",
  },
  "home-footer": {
    "padding": "50px 5vw",
    "display": "grid",
    "grid-template-columns": "1.5fr 1fr 1fr 1.4fr",
    "align-items": "start",
    "gap": "30px",
  },
  "home-hero": {
    "position": "relative",
    "min-height": "860px",
    "height": "100svh",
    "max-height": "1200px",
    "isolation": "isolate",
    "overflow": "hidden",
  },
  "home-nav": {
    "position": "absolute",
    "top": "0",
    "inset-inline": "0",
    "z-index": "10",
    "padding": "26px 3.2vw",
    "font-size": "12px",
  },
  "home-skip": {
    "position": "fixed",
    "left": "20px",
    "top": "-60px",
    "padding": "12px",
    "background": "var(--paper)",
    "z-index": "100",
  },
  "home-source": {
    "display": "flex",
    "gap": "9px",
    "align-items": "center",
  },
  "home-wordmark": {
    "position": "absolute",
    "left": "2.3%",
    "right": "2.3%",
    "bottom": "1.5%",
    "pointer-events": "none",
    "font-size": "17.45vw",
    "font-weight": "750",
    "line-height": "1.15",
    "letter-spacing": "-0.078em",
    "white-space": "nowrap",
    "animation": "intro-reveal 0.8s both",
    "opacity": "0",
    "visibility": "hidden",
  },
  "journal-caption": {
    "display": "flex",
    "align-items": "center",
    "justify-content": "space-between",
    "border-top": "1px solid #25292255",
    "margin-top": "22px",
    "padding-top": "14px",
  },
  "journal-photo": {
    "overflow": "hidden",
    "aspect-ratio": "1.12",
  },
  "lede": {
    "color": "var(--muted)",
    "max-width": "62ch",
    "font-size": "1.13rem",
    "line-height": "1.68",
    "margin-bottom": "36px",
    "text-wrap": "pretty",
  },
  "liquid": {
    "filter": "url(#liquid-wobble)",
  },
  "lqg-glass": {
    "box-shadow": "inset 0 1px 2px #fff9, inset 0 -1px 2px #ffffff70, 0 6px 20px #36474b18",
    "opacity": "0.6",
  },
  "lqg-lens": {
    "opacity": "0.45",
  },
  "marquee": {
    "position": "relative",
    "overflow": "hidden",
    "border-block": "1px solid var(--line)",
    "padding-block": "15px",
    "background": "rgba(7, 11, 24, 0.4)",
    "mask-image": "linear-gradient( 90deg, transparent, #000 8%, #000 92%, transparent )",
    "-webkit-mask-image": "linear-gradient( 90deg, transparent, #000 8%, #000 92%, transparent )",
  },
  "marquee-dot": {
    "color": "var(--cissa-soft)",
  },
  "marquee-item": {
    "font-size": "13px",
    "letter-spacing": "0.14em",
    "color": "var(--muted)",
    "white-space": "nowrap",
  },
  "marquee-seq": {
    "display": "flex",
    "align-items": "center",
    "gap": "2.6rem",
    "padding-right": "2.6rem",
  },
  "marquee-track": {
    "display": "flex",
    "width": "max-content",
    "animation": "marquee 30s linear infinite",
  },
  "material-symbol": {
    "display": "inline-block",
    "flex": "0 0 auto",
    "width": "1em",
    "height": "1em",
    "vertical-align": "-0.15em",
    "background": "currentColor",
    "-webkit-mask": "var(--symbol) center / contain no-repeat",
    "mask": "var(--symbol) center / contain no-repeat",
  },
  "mono": {
    "font-family": "\"Geist Mono\", ui-monospace, \"SF Mono\", monospace",
  },
  "nav": {
    "pointer-events": "auto",
    "display": "flex",
    "align-items": "center",
    "justify-content": "space-between",
    "gap": "1.6rem",
    "width": "min(660px, 100%)",
    "padding": "9px 14px 9px 18px",
    "border-radius": "999px",
    "transition": "box-shadow 0.35s ease, background 0.35s ease",
  },
  "nav-ext": {
    "font-size": "12.5px",
    "color": "var(--dim)",
    "padding": "8px 12px",
    "border-radius": "999px",
    "border": "1px solid transparent",
    "transition": "color 0.25s ease, border-color 0.25s ease",
  },
  "nav-links": {
    "display": "flex",
    "gap": "4px",
  },
  "nav-wrap": {
    "position": "fixed",
    "inset-inline": "0",
    "top": "18px",
    "z-index": "50",
    "display": "flex",
    "justify-content": "center",
    "padding-inline": "16px",
    "pointer-events": "none",
  },
  "outlook-body": {
    "display": "grid",
    "grid-template-columns": "1fr 1.2fr",
    "gap": "7vw",
  },
  "outlook-intro": {
    "font-size": "20px",
    "line-height": "1.4",
    "letter-spacing": "-0.025em",
  },
  "outlook-section": {
    "padding": "60px 5vw 90px",
    "scroll-margin-top": "20px",
    "padding-block": "80px 110px",
  },
  "overline": {
    "font-size": "12px",
    "letter-spacing": "0.22em",
    "color": "#97a3c9",
  },
  "paper-emblem": {
    "position": "relative",
    "width": "clamp(290px, 36vw, 540px)",
    "height": "clamp(290px, 36vw, 540px)",
  },
  "product-accordion": {
    "max-width": "1320px",
    "margin-left": "auto",
    "border-bottom": "1px solid var(--product-line)",
  },
  "product-callout-link": {
    "display": "inline-flex",
    "justify-content": "space-between",
    "gap": "90px",
    "margin-top": "32px",
    "padding-bottom": "10px",
    "border-bottom": "1px solid currentColor",
    "font-size": "14px",
  },
  "product-caption": {
    "border-top": "1px solid #25292255",
    "padding-top": "20px",
  },
  "product-captions": {
    "gap": "6vw",
    "margin-top": "28px",
  },
  "product-concept": {
    "width": "min(100%, 460px)",
  },
  "product-deck": {
    "max-width": "27ch",
    "margin-top": "35px",
    "font-size": "clamp(18px, 1.7vw, 26px)",
    "line-height": "1.27",
    "letter-spacing": "-0.035em",
  },
  "product-editorial": {
    "display": "grid",
    "grid-template-columns": "minmax(0, 1.45fr) minmax(300px, 0.7fr)",
    "min-height": "min(760px, 75vw)",
    "background": "var(--product-wash)",
  },
  "product-editorial-copy": {
    "display": "flex",
    "flex-direction": "column",
    "justify-content": "center",
    "align-items": "flex-start",
    "padding": "clamp(45px, 6vw, 104px)",
  },
  "product-editorial-image": {
    "position": "relative",
    "min-height": "500px",
    "margin": "0",
    "overflow": "hidden",
  },
  "product-feature-heading": {
    "display": "grid",
    "grid-template-columns": "minmax(0, 1.05fr) minmax(280px, 0.72fr)",
    "gap": "8vw",
    "align-items": "start",
    "max-width": "1320px",
    "margin-bottom": "clamp(48px, 8vw, 100px)",
  },
  "product-features": {
    "padding": "clamp(56px, 8vw, 130px) 5vw",
  },
  "product-footer": {
    "display": "grid",
    "grid-template-columns": "1.5fr 1fr 1fr 1.4fr",
    "align-items": "start",
    "gap": "30px",
    "padding": "50px 5vw",
  },
  "product-hero": {
    "position": "relative",
    "display": "grid",
    "grid-template-columns": "minmax(0, 1fr)",
    "min-height": "max(760px, 100svh)",
    "overflow": "hidden",
    "isolation": "isolate",
    "padding": "142px 5vw 42px",
  },
  "product-hero-copy": {
    "position": "relative",
    "z-index": "2",
    "align-self": "end",
    "max-width": "min(75rem, 100%)",
  },
  "product-hero-meta": {
    "position": "absolute",
    "z-index": "2",
    "top": "18%",
    "inset-inline": "5vw",
    "display": "flex",
    "justify-content": "space-between",
    "align-items": "flex-start",
  },
  "product-hero-object": {
    "position": "absolute",
    "z-index": "1",
    "right": "clamp(2vw, 8vw, 12vw)",
    "bottom": "clamp(12%, 17vw, 24%)",
    "width": "min(44vw, 590px)",
    "margin": "0",
  },
  "product-intro": {
    "padding": "clamp(56px, 8vw, 130px) 5vw",
  },
  "product-intro-grid": {
    "display": "grid",
    "grid-template-columns": "minmax(0, 1.05fr) minmax(280px, 0.72fr)",
    "align-items": "end",
    "gap": "8vw",
    "max-width": "1320px",
    "margin-top": "clamp(54px, 8vw, 128px)",
  },
  "product-kicker": {
    "margin-bottom": "18px",
  },
  "product-lede": {
    "color": "var(--product-muted)",
    "font-size": "clamp(16px, 1.35vw, 20px)",
    "line-height": "1.6",
    "text-wrap": "pretty",
  },
  "product-nav": {
    "position": "absolute",
    "z-index": "10",
    "top": "0",
    "inset-inline": "0",
    "padding": "26px 3.2vw",
    "font-size": "12px",
  },
  "product-nav-back": {
    "padding-block": "10px",
    "display": "flex",
    "gap": "12px",
    "align-items": "center",
  },
  "product-page": {
    "--product-paper": "#eeece4",
    "--product-ink": "#252922",
    "--product-muted": "#52584f",
    "--product-line": "#2529224d",
    "--product-wash": "#e2e3d9",
    "background": "var(--product-paper)",
    "color": "var(--product-ink)",
    "font-family": "\"DM Sans\", sans-serif",
    "line-height": "1.45",
    "min-width": "0",
    "color-scheme": "light",
  },
  "product-page-cissa": {
    "--product-wash": "#e9e0d1",
    "--product-accent": "#ad420f",
  },
  "product-page-cupboard": {
    "--product-wash": "#dce5df",
    "--product-accent": "#356b62",
  },
  "product-pairing": {
    "padding": "clamp(65px, 9vw, 140px) 5vw",
    "background": "#d9edb1",
  },
  "product-plus": {
    "justify-self": "end",
    "font-size": "29px",
    "font-weight": "300",
    "transition": "transform 0.25s ease",
  },
  "product-rule": {
    "padding-top": "17px",
    "border-top": "1px solid var(--product-line)",
  },
  "product-scroll-link": {
    "position": "absolute",
    "z-index": "2",
    "right": "5vw",
    "bottom": "42px",
    "display": "flex",
    "align-items": "center",
    "gap": "30px",
    "padding-bottom": "9px",
    "border-bottom": "1px solid var(--product-ink)",
    "font-size": "12px",
  },
  "product-skip": {
    "position": "fixed",
    "top": "-60px",
    "left": "20px",
    "z-index": "100",
    "padding": "12px",
    "background": "var(--product-paper)",
  },
  "product-sky": {
    "position": "absolute",
    "inset": "0",
    "z-index": "-2",
    "background": "#c4e2e2",
  },
  "product-still": {
    "position": "relative",
  },
  "product-study": {
    "margin": "0",
    "padding": "0 5vw 6vw",
  },
  "product-text-link": {
    "display": "inline-flex",
    "justify-content": "space-between",
    "gap": "70px",
    "margin-top": "32px",
    "padding-bottom": "10px",
    "border-bottom": "1px solid currentColor",
    "font-size": "14px",
  },
  "scroll-cue": {
    "position": "absolute",
    "bottom": "30px",
    "font-size": "11px",
    "letter-spacing": "0.3em",
    "color": "var(--dim)",
    "animation": "bob 2.6s ease-in-out infinite",
  },
  "section": {
    "position": "relative",
    "padding-block": "clamp(4rem, 9vw, 7.5rem)",
  },
  "section-index": {
    "border-top": "1px solid #25292255",
    "padding-top": "17px",
  },
  "sky": {
    "position": "fixed",
    "inset": "0",
    "z-index": "0",
    "background": "linear-gradient(180deg, #17203c 0%, #0d1428 55%, #070b18 100%)",
  },
  "sky-scrim": {
    "position": "absolute",
    "inset": "0",
    "z-index": "3",
    "background": "linear-gradient( 180deg, rgba(7, 11, 24, 0.3) 0%, rgba(7, 11, 24, 0.52) 52%, rgba(7, 11, 24, 0.94) 100% )",
  },
  "split-2": {
    "display": "grid",
    "grid-template-columns": "1.08fr 0.92fr",
    "gap": "clamp(2rem, 5vw, 4rem)",
    "align-items": "start",
  },
  "stack": {
    "display": "flex",
    "flex-direction": "column",
    "gap": "16px",
  },
  "step": {
    "padding": "22px",
  },
  "step-num": {
    "font-size": "12px",
    "letter-spacing": "0.2em",
    "color": "var(--cissa-soft)",
  },
  "steps": {
    "display": "grid",
    "grid-template-columns": "repeat(4, 1fr)",
    "gap": "18px",
  },
  "story-copy": {
    "padding": "50px 5vw",
    "display": "flex",
    "flex-direction": "column",
    "align-items": "start",
  },
  "story-footnote": {
    "margin-top": "auto",
    "padding-top": "45px",
  },
  "story-image": {
    "overflow": "hidden",
    "position": "relative",
    "background": "#efebe2",
    "min-height": "520px",
  },
  "story-image-label": {
    "position": "absolute",
    "bottom": "30px",
    "left": "30px",
  },
  "story-link": {
    "display": "inline-flex",
    "gap": "65px",
    "border-bottom": "1px solid",
    "padding-block": "10px",
    "font-size": "14px",
  },
  "story-panel": {
    "grid-area": "1 / 1",
  },
  "story-panels": {
    "display": "grid",
  },
  "strip": {
    "display": "flex",
    "flex-wrap": "wrap",
    "align-items": "center",
    "justify-content": "space-between",
    "gap": "24px",
    "padding": "32px 34px",
  },
  "strip-note": {
    "color": "var(--muted)",
    "max-width": "52ch",
  },
  "strip-title": {
    "font-size": "1.4rem",
    "font-weight": "660",
    "letter-spacing": "-0.02em",
    "margin-bottom": "6px",
  },
  "svg-defs": {
    "position": "absolute",
    "width": "0",
    "height": "0",
    "overflow": "hidden",
  },
  "symbol-asterisk": {
    "--symbol": "url(\"/icons/material-symbols-rounded/asterisk_24px.svg\")",
  },
  "symbol-downward": {
    "--symbol": "url(\"/icons/material-symbols-rounded/arrow_downward_24px.svg\")",
  },
  "symbol-outward": {
    "--symbol": "url(\"/icons/material-symbols-rounded/arrow_outward_24px.svg\")",
  },
  "t-dim": {
    "color": "#697392",
  },
  "t-ok": {
    "color": "#8ef0d2",
  },
  "t-prompt": {
    "color": "var(--cupboard-soft)",
  },
  "term": {
    "margin-top": "36px",
    "border-radius": "16px",
    "overflow": "hidden",
  },
  "term-bar": {
    "padding": "10px 18px",
    "border-bottom": "1px solid var(--line)",
    "font-size": "11.5px",
    "letter-spacing": "0.14em",
    "color": "var(--dim)",
  },
  "wi": {
    "display": "inline-block",
    "will-change": "transform",
  },
  "wrap": {
    "max-width": "1140px",
    "margin-inline": "auto",
    "padding-inline": "clamp(20px, 5vw, 44px)",
  },
};
